spring:
  application:
    name: monolith
  datasource:
    url: jdbc:h2:mem:monolith;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
  #    url: jdbc:postgresql://localhost:5432/sample
  #    username: user
  #    password: password
  #    schema:
  #      - classpath:sql/schema.sql
  #    data:
  #      - classpath:sql/ddl.sql
  jpa:
    show-sql: true
    open-in-view: false
    #    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: com.acme.monolith.common.TblSufixSpringPhysicalNamingStrategyImpl
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.acme: debug
