spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thekalinga/synechron-config-repo
server:
  port: 8888

# Refer to source of org.springframework.cloud.config.server.resource.ResourceController to know about the urls to access
